# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a lightweight Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY pyproject.toml README.md dart.py ./

# Install Python dependencies
# First install dotenv separately
RUN pip install --no-cache-dir python-dotenv
# Install this package (via PEP517) and its dependencies
RUN pip install --no-cache-dir .

# Expose no ports (stdin/stdout transport)

# Default command to run the MCP server
CMD ["python", "dart.py"]
