# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Auto-generated Dockerfile for dart-mcp
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml dart.py ./

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir .

# Copy other project files if any (e.g., uv.lock)
COPY uv.lock ./

# Set default environment (can be overridden)
ENV DART_API_KEY=

# Expose stdio transport, no ports needed

# Default command
CMD ["python", "dart.py"]
